// ============================================================
// BLOOD & BAYONETS — Force Builder Data
// Peninsular Campaign, Napoleonic Wars
// ============================================================

const SPECIAL_RULES_GLOSSARY = {
  'Artillery Crew': 'If activated with ♠ or ♥, may take a free Reload action with assigned Artillery.',
  'Assault Experts': 'May re-roll all failed results during a Shoot Save test from Defensive Fire.',
  'Armor': 'If a unit with Armor rolls a 1 for any Save, it may re-roll.',
  'Battle Hardened': 'Reduces dice rolled for a Fatigue test by one (melee only).',
  'Blood Curdling Charge': '-1 to target number for Melee test during a Charge Action.',
  'Brawlers': 'Roll additional d10 for each natural 10 rolled during a Melee Test.',
  'Bravado': 'If unit starts activation with Fatigue, roll d10 vs Resolve — on success, remove 1 Fatigue.',
  'Broadside!': 'All Artillery fired during this Commander\'s activation fires simultaneously.',
  'Cavalry': 'Free Move action each activation. Can Disengage from melee. Cannot Take Cover.',
  'Cold Blooded': 'Commander has Ruthless. Units using Command Points for Melee/Shoot also gain Ruthless.',
  'Commodore': 'When aboard a ship, Command Range increased by 12" for units on other ships.',
  'Congreve Rocket': 'May purchase a Rocket Battery support unit (see force list).',
  'Defensive Stance': 'May make a Melee Defensive Attack instead of Defensive Fire.',
  'Elan': 'Remove 1 point of Fatigue from this unit before rolling its first test each activation.',
  'Evade': 'When charged, gain 1 Fatigue to Move away instead of Defensive Fire.',
  'Expert Sailors': 'Pass ship Advanced Maneuver and Sail Setting Tests on a 4+.',
  'Expert Roundshot Skip': 'Roll 1d10 when rolling for roundshot skip; apply full result in inches.',
  'Field Gun': 'May deploy with Artillery on a field carriage, paying for the artillery piece.',
  'Grenadiers': 'Friendly units within 3" reduce target number for Resolve/Rally Tests by -1.',
  'Gunners': 'Can crew artillery on ships.',
  'Hessian Training': 'Can take a ½ shot in a Shoot Action and add Volley Fire extra dice.',
  'Highly Trained': 'Can take defensive actions (form square, defensive fire, melee defensive attack) without gaining fatigue.',
  'Horse Artillery': 'Free Move action each activation. Also gains 1 Free Unlimber/Limber action.',
  'Impetuous': 'Must Charge if able.',
  'Impact Hits': 'Extra d10s added to dice pool for a Melee attack during a Charge.',
  'Intimidation': 'If enemy takes a Resolve test from Melee, add 1 to total Resolve dice.',
  'Inspiring': 'All friendly units in Command Range may re-roll failed Rally tests when this Commander is active.',
  'Lancers': 'When charging, bestow +1 penalty to enemy Melee Save target. Negates Melee Defensive Attack vs Square.',
  'Melee Specialists': 'May re-roll all failed results during Melee Skill tests.',
  'Poor Leadership': 'When given a Command Point, unit must pass a Resolve Test or the action and point are lost.',
  'Quick': 'If activated with ♠ card and not engaged, may take a free Move action.',
  'Ruthless': 'If unit has fewer Fatigue than target during an attack, apply -1 to shoot or melee test target number.',
  'Sailors': 'Can pass ship Advanced Maneuver and Sail Setting Tests on a 5+.',
  'Skirmish': 'May form Skirmish formation.',
  'Steadfast': 'When rolling a Resolve Test as a result of a Charge, may re-roll one die.',
  'Thin Red Line': 'British unit characteristic — steady under fire.',
  'Timid': 'Unit cannot make a Charge Action.',
  'Tactician': 'Special Commander rule.',
  'Unseen Attacks': 'Spanish special rule — surprise attacks.',
  'Veteran': 'Improved combat effectiveness.',
  'Vanguard': 'May move through friendly units when advancing.',
  'Aim': 'May spend an action to Aim, reducing the target number for next Shoot action.',
  'Shrapnel': 'Artillery special ammunition type.',
};

const WEAPON_GLOSSARY = {
  'Muskets': 'Standard firearm. Range 24", 4" bands. Gains 2 Reload markers when fired.',
  'Rifles': 'Precision firearm. Range 32", 8" bands. Gains 3 Reload markers.',
  'Carbines': 'Shorter range than muskets. No 11+ hit number.',
  'Pistols': 'Range 4". Always +1 to Shoot Test target number. 2 Reload markers.',
  'Bayonets': 'Melee weapon. No special rules.',
  'Standard Melee Weapons': 'One-handed melee (swords, bayonets, axes). No special rules.',
  'Lances': 'When charging: +1 penalty to enemy Melee Save. Negates Square defensive attacks.',
  'Half Pikes': 'Last resort melee weapon. No special rules.',
  'Blunderbuss': 'Max range 12". +2 Shoot penalty unless target within 4" (+1). Fires 2d10.',
  'Grenades': '3 dice per model. Target 7+. Shoot Save 9+, ignoring cover.',
};

const CANNON_TYPES = {
  light:  { name: 'Light Cannon',  pts: 0,  notes: 'Standard light cannon.' },
  medium: { name: 'Medium Cannon', pts: 5,  notes: 'Heavier cannon with greater range.' },
  heavy:  { name: 'Heavy Cannon',  pts: 10, notes: 'Maximum firepower.' },
};

// ============================================================
// FACTIONS
// ============================================================

const FACTIONS = {

  british_army: {
    id: 'british_army',
    name: 'British Army',
    subtitle: 'The Iron Duke\'s Finest',
    color: '#bb1a1a', // red
    description: 'In 1808, the British began combating the French in the Iberian Peninsula under Arthur Wellesley, the Duke of Wellington, aided by Spanish and Portuguese allies.',
    forceRules: [
      'Congreve Rocket: May purchase a Rocket Battery support unit.',
      'Officer/N.C.O. grants British, Highlander & Irish Line the Highly Trained rule.',
      'Officer/N.C.O. grants Cavalry units the Vanguard rule.',
      'Officer/N.C.O. grants Rifle units Vanguard and Intimidation.',
      'Officer/N.C.O. grants German units (KGL, Brunswick Oels) Battle Hardened.',
      'Veteran Upgrade: May upgrade up to 2 units to Veterans.',
    ],
    allies: [
      'British Royal Navy: up to 4 Core/Support choices.',
      'Portuguese Army: up to 4 Core/Support choices.',
      'Spanish Army: up to 2 Core/Support choices.',
      'Spanish Guerrillas: up to 4 Core/Support choices.',
    ],

    commanders: [
      { id:'cap', name:'Captain', pts:5, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'1 Commander (Sword+Pistol) + 3 Infantrymen (Muskets)',
        options:['Mount Commander (+4 pts)', 'Upgrade to Veteran (+4 pts)'] },
      { id:'maj', name:'Major', pts:10, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Commander (Sword+Pistol) + 3 Infantrymen (Muskets)',
        options:['Mount Commander (+4 pts)', 'Upgrade to Veteran (+4 pts)'] },
      { id:'col', name:'Colonel', pts:23, shoot:'6/6', melee:'6/7', resolve:5, experience:'Veteran', cmdRange:6, cmdPts:3,
        composition:'1 Mounted Commander (Sword+Pistol) + 3 Infantrymen (Muskets)',
        special:['Veteran'], options:['Upgrade to Veteran (+4 pts)'] },
      { id:'cav_cmd', name:'Cavalry Commander', pts:12, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Mounted Commander + 3 Light Cavalry (Swords+Carbines)',
        special:['Cavalry'], options:['Upgrade to Veteran (+4 pts)'] },
      { id:'lillie_lt', name:'Lt. John Scott Lillie', pts:10, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'1 Commander (Sword+Pistol) + 3 Infantrymen (Muskets)',
        special:['2 units in command range may reroll 1 failed Resolve die per turn'],
        options:['Upgrade to Veteran (+4 pts)'], isNamed:true },
      { id:'plunket_cmd', name:'Rifleman Thomas Plunket', pts:14, shoot:'5/5', melee:'6/7', resolve:4, experience:'Veteran', cmdRange:6, cmdPts:1,
        composition:'Attach to British 95th Rifles unit (counts toward 6-12 models)',
        special:['While alive: unit can reroll 1 failed Shoot die per turn'], isNamed:true, isAttachment:true,
        attachTo:'95th Rifles/60th Royal American' },
      { id:'tomkinson', name:'Cornet William Tomkinson', pts:10, shoot:'7/6', melee:'6/7', resolve:6, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'Attach to British Light Dragoons unit (counts toward 4-12 models)',
        special:['While alive: unit counts as Veteran without paying upgrade cost'], isNamed:true, isAttachment:true,
        attachTo:'British Light Dragoons' },
    ],

    core: [
      { id:'brit_line', name:'British Line', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Thin Red Line'],
        formations:['Line','Square','Loose'],
        upgrades:['Officer/N.C.O.','Musician','Standard Bearer'],
        vetCost:1 },
      { id:'brit_highlander', name:'British Highlanders', costPerModel:4, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Blood Curdling Charge','Thin Red Line'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'brit_irish', name:'British Irish Line', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Brawlers'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'brit_gren', name:'British Grenadiers', costPerModel:5, shoot:'5/6', melee:'5/7', resolve:5, experience:'Veteran',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Grenadiers','Veteran','Thin Red Line'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'brit_light_flank', name:'British Light Flank Co.', costPerModel:4, shoot:'6/5', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:12, equipment:['Muskets','Bayonets'], special:['Aim','Thin Red Line'],
        formations:['Line','Square','Skirmish'], upgrades:['Officer/N.C.O.','Musician'], vetCost:1 },
      { id:'kgl', name:'King\'s German Legion', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Hessian Training','Thin Red Line'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'brunswick_oels', name:'Brunswick Oels-Jagers', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Hessian Training'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
    ],

    support: [
      { id:'brit_95th', name:'95th Rifles / 60th Royal American', costPerModel:7, shoot:'5/5', melee:'6/7', resolve:4, experience:'Veteran',
        minSize:8, maxSize:16, equipment:['Rifles','Bayonets'], special:['Skirmish','Aim','Veteran'],
        formations:['Line','Square'], upgrades:['Officer/N.C.O.','Musician'], vetCost:null },
      { id:'brit_oels_rifles', name:'Oels Jagers (Rifles)', costPerModel:5, shoot:'6/5', melee:'6/7', resolve:5, experience:'Veteran',
        minSize:6, maxSize:12, equipment:['Rifles','Bayonets'], special:['Skirmish','Aim'],
        formations:['Line','Square'], upgrades:['Officer/N.C.O.','Musician'], vetCost:1 },
      { id:'brit_heavy_drag', name:'British Heavy Dragoons', costPerModel:6, shoot:'7/6', melee:'5/6', resolve:5, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impetuous','Impact Hits (4)'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'brit_light_drag', name:'British Light Dragoons', costPerModel:4, shoot:'7/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impetuous','Impact Hits (2)'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'brit_hussars', name:'British Hussars', costPerModel:4, shoot:'7/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impetuous','Vanguard','Impact Hits (2)'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'brunswick_hussars', name:'Brunswick Hussars', costPerModel:4, shoot:'7/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impact Hits (2)','Vanguard','Impetuous','Battle Hardened'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'brit_royal_art', name:'British Royal Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim','Shrapnel'],
        cannonUpgrades:['light','medium','heavy'], vetCost:4 },
      { id:'brit_horse_art', name:'British Royal Horse Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim','Horse Artillery','Shrapnel'],
        cannonUpgrades:['light','medium'], vetCost:4 },
      { id:'brit_howitzer', name:'Howitzer', costPerCrew:17, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Howitzer', isArtillery:true, isHowitzer:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim','Shrapnel'], vetCost:4 },
      { id:'brit_rocket', name:'Rocket Battery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Rocket Battery', isArtillery:true, isRocket:true,
        equipment:['Standard Melee Weapons'], special:['Congreve Rocket'], vetCost:null },
    ],
  },

  // ─── PORTUGUESE ARMY ─────────────────────────────────────────────────────────
  portuguese_army: {
    id: 'portuguese_army',
    name: 'Portuguese Army',
    subtitle: 'Defenders of the Peninsula',
    color: '#1a5a3a',
    description: 'Trained and often led by the British, the Portuguese turned the tide against France and helped expel them from the Iberian Peninsula.',
    forceRules: [
      'Officer/N.C.O.: Portuguese units in Line within 3" of a British unit in Line lower their Resolve/Rally target by -1.',
      'Officer/N.C.O. also grants Bravado to Portuguese units.',
      'Veteran Upgrade: May upgrade up to 2 units to Veterans.',
    ],
    allies: [
      'British Army: up to 4 Core/Support choices.',
      'British Navy: up to 2 Core/Support choices.',
      'Spanish Army: 1 Core/Support choice.',
      'Spanish Guerrillas: up to 2 Core/Support choices.',
    ],
    commanders: [
      { id:'capitao', name:'Capitão', pts:5, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'1 Commander + 3 Infantrymen (Muskets)', options:['Mount Commander (+4 pts)','Upgrade to Veteran (+4 pts)'] },
      { id:'major', name:'Major', pts:10, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Commander + 3 Infantrymen (Muskets)', options:['Mount Commander (+4 pts)','Upgrade to Veteran (+4 pts)'] },
      { id:'coronel', name:'Coronel', pts:23, shoot:'6/6', melee:'6/7', resolve:5, experience:'Veteran', cmdRange:6, cmdPts:3,
        composition:'1 Mounted Commander + 3 Infantrymen', special:['Veteran'] },
      { id:'cav_cmd', name:'Cavalry Commander', pts:12, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Mounted Commander + 3 Light Cavalry', special:['Cavalry'], options:['Upgrade to Veteran (+4 pts)'] },
      { id:'pereira', name:'Capitão José Clemente Pereira', pts:10, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'1 Commander + 3 Infantrymen', special:['2 units gain Ruthless special rule'],
        options:['Mount Commander (+4 pts)','Upgrade to Veteran (+4 pts)'], isNamed:true },
      { id:'lillie_capt', name:'Captain John Scott Lillie', pts:15, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Commander + 3 Infantrymen', special:['All Cacadores units gain Ruthless'],
        options:['Mount Commander (+4 pts)','Upgrade to Veteran (+4 pts)'], isNamed:true },
    ],
    core: [
      { id:'port_line', name:'Portuguese Line', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:6, maxSize:12, equipment:['Muskets','Bayonets'], special:[],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'port_cacadores', name:'Portuguese Caçadores', costPerModel:4, shoot:'6/5', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:12, equipment:['Muskets','Bayonets'], special:['Skirmish','Aim'],
        formations:['Line','Square'], upgrades:['Officer/N.C.O.','Musician'], vetCost:1 },
    ],
    support: [
      { id:'port_atiradore', name:'Portuguese Atiradore', costPerModel:7, shoot:'5/5', melee:'6/7', resolve:5, experience:'Trained',
        minSize:6, maxSize:12, equipment:['Rifles','Bayonets'], special:['Skirmish','Aim'],
        formations:['Line','Square'], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'], vetCost:1 },
      { id:'port_dragoons', name:'Portuguese Dragoons', costPerModel:3, shoot:'8/7', melee:'7/7', resolve:7, experience:'Inexperienced',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impact Hits (3)'],
        formations:[], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'], vetCost:1 },
      { id:'port_art', name:'Portuguese Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim'],
        cannonUpgrades:['light','medium','heavy'], vetCost:4 },
      { id:'port_howitzer', name:'Field Howitzer', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Howitzer', isArtillery:true, isHowitzer:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim'], vetCost:4 },
    ],
  },

  // ─── SPANISH ARMY ────────────────────────────────────────────────────────────
  spanish_army: {
    id: 'spanish_army',
    name: 'Spanish Army',
    subtitle: 'Defenders of the Patria',
    color: '#c8a820',
    description: 'Following the proclamation that Joseph Napoleon would be king of Spain in 1808, the Spanish rose in revolt. Plagued by poor leadership, they nonetheless formed a formidable resistance.',
    forceRules: [
      'Officer/N.C.O. allows Spanish units to ignore Poor Leadership.',
      'Officer/N.C.O. grants Ruthless to Spanish units.',
      'Officer/N.C.O. grants Swiss units Tough.',
      'Officer/N.C.O. grants Irish units Blood Curdling Charge.',
      'Veteran Upgrade: May upgrade 1 unit to Veteran, 1 unit to Trained.',
    ],
    allies: [
      'British Army: 1 Core/Support choice.',
      'British Navy: 1 Core/Support choice.',
      'Portuguese Army: 1 Core/Support choice.',
      'Spanish Guerrillas: up to 4 Core/Support choices.',
    ],
    commanders: [
      { id:'capitan', name:'Capitán', pts:5, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'1 Commander + 3 Infantrymen', special:['Unseen Attacks'], options:['Mount Commander (+4 pts)','Upgrade to Veteran (+4 pts)'] },
      { id:'comandante', name:'Comandante', pts:10, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Commander + 3 Infantrymen', special:['Unseen Attacks'], options:['Mount Commander (+4 pts)','Upgrade to Veteran (+4 pts)'] },
      { id:'coronel', name:'Coronel', pts:23, shoot:'6/6', melee:'6/7', resolve:5, experience:'Veteran', cmdRange:6, cmdPts:3,
        composition:'1 Mounted Commander + 3 Infantrymen', special:['Veteran','Unseen Attacks'] },
      { id:'cav_cmd', name:'Cavalry Commander', pts:12, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Mounted Commander + 3 Light Cavalry', special:['Cavalry'], options:['Upgrade to Veteran (+4 pts)'] },
      { id:'zumalacarre', name:'Capitán Zumalacárregui', pts:12, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Commander + 3 Infantrymen',
        special:['1 unit in force may be upgraded to Trained for free (does not count toward max)'],
        options:['Mount Commander (+4 pts)'], isNamed:true },
    ],
    core: [
      { id:'span_line', name:'Spanish Line Infantry', costPerModel:2, shoot:'7/7', melee:'7/8', resolve:7, experience:'Inexperienced',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Poor Leadership'],
        formations:['Line','Square'],
        upgrades:['Officer/N.C.O.','Musician','Standard Bearer'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'span_light', name:'Spanish Light Infantry', costPerModel:2, shoot:'7/6', melee:'7/8', resolve:7, experience:'Inexperienced',
        minSize:8, maxSize:12, equipment:['Muskets','Bayonets'], special:['Skirmish','Aim','Poor Leadership'],
        formations:['Line','Square'], upgrades:['Officer/N.C.O.','Musician'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'span_gren', name:'Spanish Grenadiers', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Grenadiers','Poor Leadership'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'span_militia', name:'Militia', costPerModel:2, shoot:'7/7', melee:'7/8', resolve:8, experience:'Inexperienced',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Timid','Poor Leadership'],
        formations:['Line','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'],
        notes:'May downgrade to -1 pt per model, armed with Half Pikes only.' },
    ],
    support: [
      { id:'walloon_guards', name:'Walloon Guards', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Steadfast','Poor Leadership'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'], vetCost:1 },
      { id:'span_swiss', name:'Spanish Swiss Line', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Battle Hardened'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'], vetCost:1 },
      { id:'span_irish', name:'Spanish Irish Line', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Brawlers'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'], vetCost:1 },
      { id:'span_cuirassier', name:'Spanish Cuirassier', costPerModel:5, shoot:'8/6', melee:'7/7', resolve:7, experience:'Inexperienced',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Armor','Impact Hits (4)','Poor Leadership'],
        formations:[], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'span_dragoons', name:'Spanish Dragoons', costPerModel:3, shoot:'8/7', melee:'7/7', resolve:7, experience:'Inexperienced',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impact Hits (3)','Poor Leadership'],
        formations:[], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'span_lancer', name:'Spanish Lancers', costPerModel:3, shoot:'8/7', melee:'7/8', resolve:6, experience:'Inexperienced',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons','Lances'], special:['Cavalry','Impact Hits (3)','Poor Leadership'],
        formations:[], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'span_hussar', name:'Spanish Hussars', costPerModel:3, shoot:'8/7', melee:'7/8', resolve:6, experience:'Inexperienced',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impetuous','Vanguard','Impact Hits (2)','Poor Leadership'],
        formations:[], upgrades:['Officer/N.C.O.','Standard Bearer','Musician'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'span_art', name:'Field Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim'],
        cannonUpgrades:['light','medium','heavy'], vetCost:4 },
      { id:'span_horse_art', name:'Horse Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim','Horse Artillery'],
        cannonUpgrades:['light','medium'], vetCost:4 },
      { id:'span_howitzer', name:'Field Howitzer', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Howitzer', isArtillery:true, isHowitzer:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim'], vetCost:4 },
    ],
  },

  // ─── FRENCH ARMY ─────────────────────────────────────────────────────────────
  french_army: {
    id: 'french_army',
    name: 'French Army',
    subtitle: 'La Grande Armée',
    color: '#2450a0',
    description: 'The French in Spain were an international force — troops from France, Germany, Poland, Italy and beyond. The "Spanish Ulcer" would ultimately drain Napoleon\'s resources for little gain.',
    forceRules: [
      'Officer/N.C.O. grants French units Elan.',
      'Officer/N.C.O. grants Swiss units Tough.',
      'Officer/N.C.O. grants Northern Italian units Bravado.',
      'Officer/N.C.O. allows Neapolitan units to ignore Poor Leadership.',
      'Officer/N.C.O. grants German units Battle Hardened.',
      'Officer/N.C.O. grants Polish units Blood Curdling Charge.',
      'Officer/N.C.O. grants Irish units Blood Curdling Charge.',
      'Officer/N.C.O. grants Dutch units Steadfast.',
      'Veteran Upgrade: May upgrade up to 2 units to Veterans.',
    ],
    allies: [
      'French Navy: up to 2 Core/Support choices.',
      'Spanish Army of Joseph Bonaparte: up to 2 Core/Support choices.',
    ],
    commanders: [
      { id:'capitaine', name:'Capitaine', pts:5, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'1 Commander + 3 Infantrymen', options:['Mount Commander (+4 pts)','Upgrade to Veteran (+4 pts)'] },
      { id:'major', name:'Major', pts:10, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Commander + 3 Infantrymen', options:['Mount Commander (+4 pts)','Upgrade to Veteran (+4 pts)'] },
      { id:'colonel', name:'Colonel', pts:23, shoot:'6/6', melee:'6/7', resolve:5, experience:'Veteran', cmdRange:6, cmdPts:3,
        composition:'1 Mounted Commander + 3 Infantrymen', special:['Veteran'] },
      { id:'cav_cmd', name:'Cavalry Commander', pts:12, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Mounted Commander + 3 Light Cavalry', special:['Cavalry'], options:['Upgrade to Veteran (+4 pts)'] },
      { id:'de_rocca', name:'Lt. Albert Jean Michel de Rocca', pts:14, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Mounted Commander + 3 Light Cavalry',
        special:['Cavalry','Hussar units under his command lose Impetuous'], isNamed:true },
    ],
    core: [
      { id:'fr_line', name:'French Line Infantry', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:[],
        formations:['Line','Square','Loose','Attack Column'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_light', name:'French Light Infantry', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:[],
        formations:['Line','Square','Loose','Attack Column'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_gren', name:'French Grenadiers', costPerModel:5, shoot:'5/6', melee:'5/7', resolve:5, experience:'Veteran',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Grenadiers','Veteran'],
        formations:['Line','Square','Loose','Attack Column'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_swiss', name:'Swiss Line Infantry', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Battle Hardened'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_n_italian', name:'Northern Italian Line', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Intimidation'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_neapolitan', name:'Neapolitan Line Infantry', costPerModel:2, shoot:'7/7', melee:'7/8', resolve:7, experience:'Inexperienced',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Poor Leadership'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'] },
      { id:'fr_german', name:'German Line Infantry', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Hessian Training'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_polish', name:'Polish Line Infantry', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Assault Experts'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_irish', name:'Irish Line Infantry', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Brawlers'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_dutch', name:'Dutch Line Infantry', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Bravado'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_gend_foot', name:'Gendarmes d\'Espagne (Foot)', costPerModel:6, shoot:'5/6', melee:'5/7', resolve:5, experience:'Veteran',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Steadfast'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'] },
    ],
    support: [
      { id:'fr_voltigeurs', name:'Voltigeurs', costPerModel:4, shoot:'6/5', melee:'6/7', resolve:6, experience:'Trained',
        minSize:6, maxSize:12, equipment:['Muskets','Bayonets'], special:['Skirmish','Aim'],
        formations:['Line','Square'], upgrades:['Officer/N.C.O.','Musician'], vetCost:1 },
      { id:'fr_polish_lancer', name:'Polish Lancers of the Guard', costPerModel:7, shoot:'7/6', melee:'5/6', resolve:3, experience:'Veteran',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons','Lances'], special:['Cavalry','Impact Hits (3)','Veteran'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'] },
      { id:'fr_cuirassier', name:'French Cuirassier', costPerModel:6, shoot:'7/6', melee:'5/6', resolve:6, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impact Hits (4)'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_dragoon', name:'French Dragoons', costPerModel:5, shoot:'7/6', melee:'6/6', resolve:6, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impact Hits (3)'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_vistula', name:'Vistula Lancers', costPerModel:5, shoot:'7/6', melee:'6/6', resolve:6, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons','Lances'], special:['Cavalry','Impact Hits (3)','Lancers'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_chasseur', name:'Chasseurs à Cheval', costPerModel:4, shoot:'7/6', melee:'6/6', resolve:6, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impact Hits (2)'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_hussars', name:'Hussars', costPerModel:4, shoot:'7/6', melee:'6/6', resolve:6, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impetuous','Impact Hits (2)'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_gend_mount', name:'Gendarmes d\'Espagne (Mounted)', costPerModel:6, shoot:'7/6', melee:'5/6', resolve:5, experience:'Veteran',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impact Hits (3)','Steadfast'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'fr_gend_lancers', name:'Gendarmes d\'Espagne (Lancers)', costPerModel:6, shoot:'7/6', melee:'5/6', resolve:5, experience:'Trained',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons','Lances'], special:['Cavalry','Impact Hits (3)','Lancers'],
        formations:[], upgrades:['Officer/N.C.O.','Musician'] },
      { id:'fr_art', name:'Field Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim','Expert Roundshot Skip'],
        cannonUpgrades:['light','medium','heavy'], vetCost:4 },
      { id:'fr_horse_art', name:'Horse Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim','Horse Artillery','Expert Roundshot Skip'],
        cannonUpgrades:['light','medium'], vetCost:4 },
      { id:'fr_howitzer', name:'Howitzer', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Howitzer', isArtillery:true, isHowitzer:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim','Veteran'], vetCost:4 },
    ],
  },

  // ─── SPANISH GUERRILLAS ──────────────────────────────────────────────────────
  spanish_guerrillas: {
    id: 'spanish_guerrillas',
    name: 'Spanish Guerrillas',
    subtitle: 'La Guerra de Guerrillas',
    color: '#8b6a00',
    description: 'The guerrillas harassed French supply lines and rear areas across the Iberian Peninsula. Some bands grew into armies with artillery and cavalry of their own.',
    forceRules: [
      'Guerrilla specialists — suited for ambush and asymmetric warfare.',
      'Officer/N.C.O. grants Ruthless to units.',
    ],
    allies: [
      'British Army: up to 2 Core/Support choices.',
      'Spanish Army: up to 2 Core/Support choices.',
    ],
    commanders: [
      { id:'guerrilla_cap', name:'Guerrilla Capitán', pts:5, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'1 Commander + 3 Guerrillas', special:['Unseen Attacks'], options:['Mount Commander (+4 pts)'] },
      { id:'guerrilla_cmd', name:'Guerrilla Comandante', pts:10, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Commander + 3 Guerrillas', special:['Unseen Attacks'], options:['Mount Commander (+4 pts)'] },
    ],
    core: [
      { id:'guerrilla_foot', name:'Guerrilla Infantry', costPerModel:2, shoot:'7/6', melee:'7/7', resolve:6, experience:'Inexperienced',
        minSize:6, maxSize:12, equipment:['Muskets','Bayonets'], special:['Skirmish','Unseen Attacks'],
        formations:['Loose'], upgrades:['Officer/N.C.O.','Musician'],
        trainedUpgrade:'1 pt per model (loses Inexperienced, gains Trained)' },
    ],
    support: [
      { id:'guerrilla_mounted', name:'Guerrilla Cavalry', costPerModel:3, shoot:'7/6', melee:'7/7', resolve:6, experience:'Inexperienced',
        minSize:4, maxSize:8, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Vanguard'],
        formations:[], upgrades:['Officer/N.C.O.'], vetCost:1 },
    ],
  },

  // ─── JOSEPH BONAPARTE ARMY ───────────────────────────────────────────────────
  joseph_army: {
    id: 'joseph_army',
    name: 'Army of Joseph Bonaparte',
    subtitle: 'Josefinos — Spanish Loyalists',
    color: '#3a1a6b',
    description: 'Following Joseph Bonaparte becoming king of Spain, civil war broke out. The Josefinos fought for their French-installed king, plagued by command issues and limited effectiveness.',
    forceRules: [
      'Officer/N.C.O. allows Spanish units to ignore Poor Leadership.',
      'Officer/N.C.O. grants Irish units Blood Curdling Charge.',
      'Unit Upgrades: May upgrade 1 unit to Veteran, 1 unit to Trained.',
    ],
    allies: [
      'French Army: up to 4 Core/Support choices.',
      'French Navy: up to 2 Core/Support choices.',
    ],
    commanders: [
      { id:'capitan', name:'Capitán', pts:5, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:1,
        composition:'1 Commander + 3 Infantrymen', options:['Mount Commander (+4 pts)'] },
      { id:'comandante', name:'Comandante', pts:10, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Commander + 3 Infantrymen', options:['Mount Commander (+4 pts)'] },
      { id:'coronel', name:'Coronel', pts:17, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:"6\"", cmdPts:3,
        composition:'1 Commander + 3 Infantrymen', options:['Mount Commander (+4 pts)','Replace up to 3 infantrymen with Musicians or Flagbearers (6 pts each)'] },
      { id:'cav_cmd', name:'Cavalry Commander', pts:12, shoot:'6/6', melee:'6/7', resolve:5, experience:'Trained', cmdRange:6, cmdPts:2,
        composition:'1 Mounted Commander + 3 Light Cavalry', special:['Cavalry'] },
    ],
    core: [
      { id:'jos_line', name:'Spanish Line Infantry', costPerModel:2, shoot:'7/7', melee:'7/8', resolve:7, experience:'Inexperienced',
        minSize:6, maxSize:12, equipment:['Muskets','Bayonets'], special:['Poor Leadership'],
        formations:['Line','Square'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
    ],
    support: [
      { id:'jos_guard_gren', name:'Guard Grenadiers', costPerModel:3, shoot:'6/6', melee:'6/7', resolve:6, experience:'Trained',
        minSize:8, maxSize:16, equipment:['Muskets','Bayonets'], special:['Grenadiers','Poor Leadership'],
        formations:['Line','Square','Loose'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'], vetCost:1 },
      { id:'jos_voltigeurs', name:'Spanish Voltigeurs', costPerModel:3, shoot:'7/6', melee:'7/8', resolve:6, experience:'Inexperienced',
        minSize:6, maxSize:12, equipment:['Muskets','Bayonets'], special:['Skirmish','Aim','Poor Leadership'],
        formations:['Line','Square'], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'jos_heavy_cav', name:'Spanish Heavy Cavalry', costPerModel:4, shoot:'8/6', melee:'7/7', resolve:7, experience:'Inexperienced',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impact Hits (4)','Poor Leadership'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'jos_lancers', name:'Spanish Lancers', costPerModel:3, shoot:'8/7', melee:'7/8', resolve:6, experience:'Inexperienced',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons','Lances'], special:['Cavalry','Impact Hits (3)','Poor Leadership'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'jos_hussars', name:'Spanish Hussars', costPerModel:3, shoot:'8/7', melee:'7/8', resolve:6, experience:'Inexperienced',
        minSize:4, maxSize:12, equipment:['Carbines','Standard Melee Weapons'], special:['Cavalry','Impetuous','Vanguard','Impact Hits (2)','Poor Leadership'],
        formations:[], upgrades:['Officer/N.C.O.','Musician','Standard Bearer'],
        trainedUpgrade:'1 pt per model (loses Poor Leadership, gains Battle Hardened)' },
      { id:'jos_art', name:'Field Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim'],
        cannonUpgrades:['light','medium','heavy'], vetCost:4 },
      { id:'jos_horse_art', name:'Horse Artillery', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Cannon', isArtillery:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim','Horse Artillery','Expert Roundshot Skip'],
        cannonUpgrades:['light','medium'], vetCost:4 },
      { id:'jos_howitzer', name:'Field Howitzer', costPerCrew:15, shoot:'5/6', melee:'6/7', resolve:6, experience:'Trained',
        composition:'4 Gunners + 1 Howitzer', isArtillery:true, isHowitzer:true,
        equipment:['Standard Melee Weapons'], special:['Artillery Crew','Aim'], vetCost:4 },
    ],
  },
};

// Point guidance
const POINT_GUIDANCE = [
  { pts: 150, label: 'Skirmish (~1 hour)', desc: 'Great for beginners.' },
  { pts: 250, label: 'Standard (~2 hours)', desc: 'Good balanced game.' },
  { pts: 400, label: 'Large Battle (evening)', desc: 'Full-scale engagement.' },
];

// Universal unit upgrades costs (per model, when applying)
const UNIT_UPGRADE_COSTS = {
  'Officer/N.C.O.': 'double model cost',
  'Standard Bearer': 'double model cost',
  'Musician': 'double model cost',
};
